version: '3'
services:
  api:
    command: npm run start:dev # development
    volumes: # development
      - ./api/index.js:/usr/src/app/index.js
  web:
    command: npm run start:devserver # development
    ports:
      - "4000:3000"
      - "8080:8080" # development
    volumes: # development
      - ./web/index.js:/usr/src/app/index.js
      - ./web/views:/usr/src/app/views
      - ./web/src:/usr/src/app/src
      - ./web/static:/usr/src/app/static
    environment:
      - DIST_URL=http://localhost:8080/dist
      - APP_ENV=development
      - WEBPACK_PORT=8080