version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
     - ./api/.env
    ports:
      - "4001:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file:
      - ./web/.env
    ports:
      - "4000:3000"
    depends_on:
      - api